<?php require 'templates/layout/header.phtml' ?>

<h2>Lista de Autores</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Biografía</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody class="table-group-divider"> 

        <?php foreach($autores as $autor): ?>
            <tr que_id="<?=$autor->idcarrera?>">
                <td data-label="Nombre"><a href="showLibrosxAutor/<?=$autor->idautor?>"> <?=$autor->nombre?> </a></td>
                <td data-label="Biografía"><?=$autor->biografia?></td>
                <td data-label="Acciones">
                    <a href="showEditAutor/<?=$autor->idautor?>"   class="btn btn-sm btn-success"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                    &nbsp; 
                    <a href="showDeleteAutor/<?=$autor->idautor?>" class="btn btn-sm btn-danger"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                </td>
            </tr>
        <?php endforeach; ?> 

    </tbody>
</table>

<p class="mt-3"><small>Mostrando <?=$count?> autores</small></p>
<p id="mensaje"></p>

<?php require 'templates/barra_inferior_autores.phtml' ?>

<?php require 'templates/layout/footer.phtml' ?>
